### ISSUE TITLE
Stopping tendermint node doesn't release a lock

### ISSUE THREAD

**Issue by EnchanterIO** [lightstreams-network/lightchain#94]
## Steps to reproduce

```
n.Start()
n.Stop()
n.Start()

Error initializing DB: resource temporarily unavailable.
```

Stopping node, which attempts to stop ethereum and tendermint services, doesn't release the lock from tendermint's Level DB. Only stopping the entire unix process does.

Due to this issue we can't write some tracing tests that require a full node restart within the same unix process.

**Comment by ggarri** [comment]
Fixed on [Tendermint v0.31.0](https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md#breaking-changes-3)

**Comment by EnchanterIO** [comment]
What particular Tendermint task is fixing this issue @ggarri?

It's still happening:
```
INFO [05-30|10:58:02.872] Starting consensus engine...             engine=node
Node resulted in panic: Error initializing DB: resource temporarily unavailable. 
```

**Comment by EnchanterIO** [comment]
Blocked meanwhile Tendermint fixes it.
